name: Run A2F2 motor tests
on:
  workflow_dispatch:    # permite executar manualmente pelo Actions > Run workflow
  push:
    branches: [ "main", "principal" ]   # cobre os dois nomes possíveis
    paths:
      - "**/*.py"
