name: Run A2F2 motor tests

on:
  workflow_dispatch:
  push:
    branches: [ "main", "principal" ]
    paths:
      - '**/*.py'

jobs:
  run-motor-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
